export const BENEFITS_LIST = [
  "Kantine",
  "Fortbildungen",
  "flexible Arbeitszeiten",
  "Fahrtkostenerstattung",
  "Firmenwagen",
  "Essenszulage",
  "Kinderbetreuung",
  "Homeoffice",
  "Mitarbeiter Events",
  "Arbeitskleidung wird gestellt",
  "bezahlte Ausbildungsmöglichkeiten",
  "Mitarbeiterbeteiligung",
  "Mitarbeiterhandy",
  "Mitarbeiterrabatte",
  "Private Internetnutzung erlaubt",
  "Parkplatz",
  "betriebliche Altersvorsorge",
  "Gesundheitsmaßnahmen",
  "Betriebsarzt",
  "Coaching",
  "gute Verkehrsanbindung",
  "barrierefrei",
  "Hunde geduldet"
];

// Mapping from keywords (found in text) to canonical Benefit strings (from BENEFITS_LIST)
export const BENEFIT_KEYWORDS: Record<string, string> = {
  "kantine": "Kantine",
  "fortbildung": "Fortbildungen",
  "flexible": "flexible Arbeitszeiten",
  "fahrtkosten": "Fahrtkostenerstattung",
  "firmenwagen": "Firmenwagen",
  "essenszulage": "Essenszulage",
  "kinderbetreuung": "Kinderbetreuung",
  "homeoffice": "Homeoffice",
  "event": "Mitarbeiter Events",
  "arbeitskleidung": "Arbeitskleidung wird gestellt",
  "ausbildung": "bezahlte Ausbildungsmöglichkeiten",
  "mitarbeiterbeteiligung": "Mitarbeiterbeteiligung",
  "handy": "Mitarbeiterhandy",
  "rabatt": "Mitarbeiterrabatte",
  "internet": "Private Internetnutzung erlaubt",
  "parkplatz": "Parkplatz",
  "altersvorsorge": "betriebliche Altersvorsorge",
  "gesundheit": "Gesundheitsmaßnahmen",
  "betriebsarzt": "Betriebsarzt",
  "coaching": "Coaching",
  "verkehrsanbindung": "gute Verkehrsanbindung",
  "barrierefrei": "barrierefrei",
  "hund": "Hunde geduldet"
};
