export const BENEFITS_LIST = [
  "Kantine",
  "Fortbildungen",
  "flexible Arbeitszeiten",
  "Fahrtkostenerstattung",
  "Firmenwagen",
  "Essenszulage",
  "Kinderbetreuung",
  "Homeoffice",
  "Mitarbeiter Events",
  "Arbeitskleidung wird gestellt",
  "bezahlte Ausbildungsmöglichkeiten",
  "Mitarbeiterbeteiligung",
  "Mitarbeiterhandy",
  "Mitarbeiterrabatte",
  "Private Internetnutzung erlaubt",
  "Parkplatz",
  "betriebliche Altersvorsorge",
  "Gesundheitsmaßnahmen",
  "Betriebsarzt",
  "Coaching",
  "gute Verkehrsanbindung",
  "barrierefrei",
  "Hunde geduldet"
];
